//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHouseWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valot
    {
        public int ValoId { get; set; }
        public string Huone { get; set; }
        public Nullable<bool> ValoOff { get; set; }
        public Nullable<bool> ValoOn33 { get; set; }
        public Nullable<bool> ValoOn66 { get; set; }
        public Nullable<bool> ValoOn100 { get; set; }
    }
}
